### ISSUE TITLE
Make control able to hold and slide to seek

### ISSUE THREAD

**Issue by moonspeak** [zst123/StatusCursorControl#6]
Would it be possible to make it so the user can hold and slide their finger to move the cursor precisely, rather than having to make small sliding increments? In effect, it would work just like the status bar brightness control slider (in CM or Gravitybox) or the sliding cursor motion in iOS.

**Comment by zst123** [comment]
It does that already "like the status bar brightness control slider (in CM or Gravitybox)"

**Comment by moonspeak** [comment]
I think I didn't explain very well what I meant. By "like the status bar brightness control slider (in CM or Gravitybox)", I meant such that the finger can be held down on the bar and dragged and the cursor would move simultaneously with the user's finger. As the module is, I cannot get it to work this way; it only moves the cursor incrementally by 'flicking' across the status bar.

**Comment by moonspeak** [comment]
Wow. Ok, my apologies. I now realize, after using it in Chrome, that the module does indeed work this way. The only app I had previously ever tested it in, Textra (SMS app) simply has issues with it. What a shame. But thank you for this module.
